project:
  type: website
  # output directory used on gh-pages branch. format: YYMM
  output-dir: "r-plots"
  render: 
    - "!README.md"
    - "!LICENSE"
    - "!LICENSE.md"
    - "!scripts"
    - "!tmprepo"
    - "!*.Rmd"
    - "!*.md"
    - "*.qmd"

website:
  image: "assets/images/banner.webp"
  favicon: "assets/favicon.png"
  navbar:
    logo: "assets/logos/nbis-scilifelab.png"
    logo-alt: "logo"
    right:
      - text: "Home"
        href: "index.html"
      - text: "Schedule"
        href: "home_schedule.html"
      - text: "Contents"
        href: "home_contents.html"
      - text: "Precourse"
        href: "home_precourse.html"
      - text: "Info"
        href: "home_info.html"
      - icon: "github"
        href: "https://github.com/NBISweden/workshop-infravis/"
  page-footer:
    border: false
    left: "{{< meta current_year >}} [NBIS](https://nbis.se) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"
  site-url: "https://nbisweden.github.io/workshop-infravis/r-plots/"
  open-graph: true

format:
  html:
    quarto-required: ">=1.4.0"
    include-in-header: "assets/include_head.html"
    theme: "assets/css/styles.scss"
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: false
    code-tools: false
    code-copy: true
    code-overflow: wrap
    df-print: paged
    standalone: false
    fig-align: left
    title-block-banner: "assets/images/banner.webp"
    callout-icon: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    image: "assets/images/featured.webp"
    lightbox: auto
  revealjs:
    quarto-required: ">=1.4.0"
    include-in-header: "assets/include_head.html"
    theme: ["default","assets/css/slides.scss"]
    df-print: paged
    width: 1280
    height: 720
    transition: "fade"
    transition-speed: "fast"
    smaller: false
    incremental: false
    scrollable: false
    slide-level: 2
    slide-number: true
    progress: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    fig-align: left
    chalkboard: true
    callout-icon: true
    image: "/assets/images/featured.webp"
    hero: "/assets/images/slide-hero.webp"
    title-slide-attributes:
      data-background-image: "/assets/images/cover.webp"
      data-background-size: "cover"
      data-background-opacity: "1"
    header-logo-left: /assets/logos/nbis.png
    header-logo-left-height: 25px
    header-logo-left-url: "https://nbisweden.github.io/workshop-infravis/r-plots/home_contents.html"
    header-logo-right: /assets/logos/scilifelab.png
    header-logo-right-height: 25px
    header-logo-right-url: "https://nbisweden.github.io/workshop-infravis/r-plots/home_contents.html"
    template-partials:
      - "assets/title-slide.html"
      
bibliography: references.bib
csl: apa.csl

knitr:
  opts_chunk:
    results: hold

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: true

filters:
  - assets/custom.lua
  - assets/fold-results.lua
  - reveal-logo

# location is used to render the info page
# location options are linkoping, lund, umea, stockholm, uppsala or online
# one or more separated by commas or semicolon.
location: online
assistants:
 - "LM: Lokesh Mano"
 - "KK: Katja Kozjek"
 - "MV: Massimiliano Volpe"

schedule_message: "Breaks are planned as 2 X 10 minutes leg stretcher each day."
colors:
  primary: "#95b540"
  secondary: "#E9F2D1"

# r packages needed for the workshop
# used in home_precourse.Rmd
# split into cran and bioc packages
# if a package is needed by students and repo, add to _student
# if a package is only needed for repo (build, rendering etc), add to _repo
# NOT USED FOR GITHUB ACTIONS
packages:
  packages_cran_student:
   - BiocManager
   - remotes
   - dplyr
   - ggplot2
   - pheatmap
   - stringr
   - tidyr
  packages_bioc_student:
  packages_github_student:
  packages_cran_repo:
   - here
   - htmlTable
   - knitr
   - leaflet
   - lubridate
   - readxl
   - writexl
   - yaml
  packages_bioc_repo:
  packages_github_repo:
